# Generated by Django 5.0.7 on 2024-07-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocCouriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriers',
            name='Avatar',
            field=models.ImageField(blank=True, default='media/defolt_avatar.png', null=True, upload_to='media/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='couriers',
            name='Experience',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couriers',
            name='Phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='couriers',
            name='Rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couriers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
