# Generated by Django 5.0.7 on 2024-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocCouriers', '0002_couriers_avatar_couriers_experience_couriers_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriers',
            name='count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couriers',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='couriers',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
