# Generated by Django 5.0.7 on 2024-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocCouriers', '0003_couriers_count_couriers_latitude_couriers_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriers',
            name='Phone',
            field=models.CharField(blank=True, default='8(888)555-55-35', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='couriers',
            name='name',
            field=models.CharField(blank=True, default='Max', max_length=50, null=True),
        ),
    ]
