# Generated by Django 5.0.7 on 2024-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocCouriers', '0004_alter_couriers_phone_alter_couriers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriers',
            name='latitude',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='couriers',
            name='longitude',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
