# Generated by Django 5.0.7 on 2024-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocCouriers', '0005_alter_couriers_latitude_alter_couriers_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOrderId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
            ],
        ),
    ]
