# Generated by Django 5.0.7 on 2024-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocCouriers', '0006_listorderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriers',
            name='Avatar',
        ),
        migrations.RemoveField(
            model_name='couriers',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='couriers',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='couriers',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='couriers',
            name='count',
        ),
        migrations.AddField(
            model_name='couriers',
            name='courier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couriers',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='couriers',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='couriers',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='couriers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='couriers',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
